services:
  - type: web
    name: land-commerce-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: BéninMarket
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: land-commerce-api
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: metro.proxy.rlwy.net
      - key: DB_PORT
        value: 17739
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: oYKfRuqupZDockupKNDqavnlwlmpUBIs
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
